name: towfix
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  # cupertino_icons: ^1.0.2
  # firebase_core: ^2.9.0
  # google_fonts: ^4.0.4
  # flutter_riverpod: ^2.3.6
  # flutter_svg: ^2.0.7
    
  freezed_annotation: ^2.1.0

  rating: ^1.0.0-dev.1
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.4.0
  flutter_polyline_points: ^2.0.0



 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  google_fonts: ^5.1.0
  riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  go_router: ^9.0.0
  firebase_auth: ^4.9.0
  # image_picker: ^1.0.4
  wolt_modal_sheet: ^0.1.2

  # media
  camera: ^0.10.4
  camerawesome: ^1.2.1
  image_picker: ^1.0.4

  riverpod_annotation: ^2.1.5
  ui_common:
    path: packages/ui_common/


  permission_handler: ^10.2.0
  hive_flutter: ^1.1.0
  hive: 2.2.3  
  dio: ^5.3.2
  cloud_firestore: ^4.9.1
  intl: ^0.18.1
  flutter_riverpod: ^2.4.0
  dartz: ^0.10.1
  firebase_storage: ^11.2.6
  font_awesome_flutter: ^10.5.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  geocoding: ^2.1.0
  geolocator: ^10.0.1
    # internet
  internet_connection_checker_plus: ^2.0.0
  # secrets
  envied: ^0.3.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.0.15
  #generate flutter hive type adapters
  hive_generator: ^2.0.0
  # generate splash screens
  flutter_native_splash: ^2.0.5
  # generate launcher icons
  flutter_launcher_icons: ^0.9.3
  # Code generation
  json_serializable: ^6.7.1
  freezed: ^2.1.0+1
  riverpod_generator: ^2.2.3
  envied_generator: ^0.3.0+3


flutter_native_splash:
  image: "assets/static/splash.png"
  color: "#07005C"

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/static/splash.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/static/
    - assets/svg/